"use client";

import { CalendarClock, CheckCircle2, MessageCircle } from "lucide-react";

type Lead = Record<string, any>;
const date = (value?: string) => value ? new Intl.DateTimeFormat("pt-BR", { dateStyle: "short", timeZone: "America/Sao_Paulo" }).format(new Date(value)) : "Sem data";

export function CrmToday({ metrics, queue, onLead, onWhatsApp, onDone }: { metrics: any; queue: Lead[]; onLead: (lead: Lead) => void; onWhatsApp: (lead: Lead) => void; onDone: (lead: Lead) => void }) {
  const values = metrics?.metrics || {};
  const cards = [["Atrasadas", values.overdue || 0, "Resolva primeiro"], ["Para hoje", values.dueToday || 0, "Follow-ups programados"], ["Sem tarefa", values.leadsWithoutTask || 0, "Leads novos para planejar"], ["Sem responsavel", values.noOwner || 0, "Distribua com a equipe"]];
  return <div className="space-y-4"><section className="surface-panel p-5"><div className="flex items-start gap-3"><CalendarClock className="mt-1 text-violet-600" size={20}/><div><h2 className="text-lg font-black">Agenda de hoje</h2><p className="mt-1 text-sm font-semibold text-slate-500">Aqui entram apenas tarefas vencidas e follow-ups marcados para hoje. Leads sem tarefa ficam separados para voce planejar, sem virar uma fila confusa.</p></div></div></section><section className="grid grid-cols-2 gap-3 xl:grid-cols-4">{cards.map(([label, value, helper]) => <div key={String(label)} className="surface-panel p-4"><p className="text-xs font-black uppercase text-slate-500">{label}</p><p className="mt-2 text-2xl font-black text-slate-950">{value}</p><p className="mt-1 text-xs font-bold text-slate-500">{helper}</p></div>)}</section><section className="surface-panel overflow-hidden"><div className="border-b p-5"><h2 className="text-lg font-black">Tarefas que exigem acao</h2></div><div className="divide-y">{queue.map((lead) => <div key={lead.id} className="flex flex-wrap items-center gap-3 p-4"><button className="min-w-52 text-left font-black" onClick={() => onLead(lead)}>{lead.companyName || lead.name}<span className="block text-xs font-semibold text-slate-500">{lead.city || "Cidade nao informada"} · {lead.nextAction || "Sem descricao"}</span></button><span className={`rounded-full px-2 py-1 text-xs font-bold ${lead.nextFollowUp && new Date(lead.nextFollowUp) < new Date(new Date().setHours(0,0,0,0)) ? "bg-red-50 text-red-700" : "bg-violet-50 text-violet-700"}`}>{date(lead.nextFollowUp)}</span><div className="ml-auto flex gap-2"><button className="icon-button" onClick={() => onWhatsApp(lead)} title="Abrir WhatsApp"><MessageCircle size={17}/></button><button className="secondary-action px-3 py-2" onClick={() => onDone(lead)}><CheckCircle2 size={15}/> Concluir</button></div></div>)}{!queue.length ? <p className="p-8 text-center font-bold text-slate-500">Nenhuma tarefa de follow-up para hoje. Planeje os leads sem tarefa para manter a prospeccao andando.</p> : null}</div></section></div>;
}
